version: "3.9"
services:
  euer:
    build: .
    container_name: euer
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - euer_data:/app/data
    env_file:
      # Datei .env muss auf dem Pi liegen (nicht im Repo!)
      - .env
    deploy:
      resources:
        limits:
          memory: 64M

volumes:
  euer_data:
